### ISSUE TITLE
Recommend using z8::fix32

### ISSUE THREAD

**Issue by samhocevar** [0xcafed00d/tac08#1]
Hi, I’ve seen that you implemented the API mostly with `int` types. You should be aware that some functions use fractional arguments, for instance [`w` and `h` in `spr()`](http://pico-8.wikia.com/wiki/Spr) which let you blit partial sprites.

If you want better compatibility, I suggest using the `z8::fix32` fixed-point type from z8lua (which can be cast to and back from `int`, `float`, etc.) in all API calls.

(Also if you would like to collaborate I’d be glad to share insight!)

**Comment by 0xcafed00d** [comment]
Hi Sam, 

Thanks for the info regarding the fractional parameters, i was not at all aware that you could do that, although its usefulness is questionable when the much more powerful sspr is available. I'm finding lots of small compatibility edge cases like this as I go forwards. Currently I'm only trying to get own carts to run correctly, and haven't gone down the rabbit hole of other peoples carts yet. 

My main reason for building this thing (I do need a better name for it) is that my new pico8 game needs to be able to save the levels that players create to solve the puzzles to disk, which cant currently be done with current pico8 implementation. Plus its a fun little project, its been a long time since I've written a sprite routine (Atari ST i think) . :-)

next on my todo list is 
fill patterns
clicle drawing,
mouse support 
sound. 

Oh thanks for building z8lua, that saved me loads of time, if you had have made that I probably would have just used luajit, and not bothered with compatibility.

Cheers, 
Lee
