### ISSUE TITLE
Feature Request: Microcontroller (esp32 or arm)

### ISSUE THREAD

**Issue by DerfOh** [0xcafed00d/tac08#10]
How difficult would it be to port this to esp32? I'd love to contribute a hardware design but I lack the C skills to pull this off in software.

**Comment by 0xcafed00d** [comment]
Porting the code is simple, I ported it to a teensy 4.0 a few years ago: [Prototype pico8 handheld console running Fuz](https://www.youtube.com/watch?v=zokRzpbqv9U)

The problem is performance. The Teensy 4 has a 600Mhz arm processor and 1MB of ram, and most games did not fit in memory and a lot that did did not run fast enough, and both are performance and space problems are due to the LUA interpreter. 

Its much cheaper to put the real pico8 on a raspberry pi zero.
